//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReaderDiary
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookGenre
    {
        public int id_book_genre { get; set; }
        public int id_passport { get; set; }
        public int id_genre { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual Passport Passport { get; set; }
    }
}
